name: machinelearning
channels:
        - conda-forge

dependencies:
        - python=3.6
        - opencv
        - jupyter
        - numpy
        - matplotlib
        - boto3
        - scikit-learn